#!/usr/bin/env bash
export $(dbus-launch)
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

# Set background
nitrogen --restore &

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Start polybar based on the number of monitors found
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar -c "~/.config/polybar/config.ini" bar1 &> /dev/null &
  done <<< "$monitors"
fi

# Start EasyEffects
if ! pgrep -x "easyeffects" > /dev/null; then
    easyeffects --gapplication-service &
fi

# Disable screen blanking and DPMS
xset s off
xset s noblank
xset dpms 0 0 0
xset -dpms
